### PR TITLE
Fix the project CLI flag

### LINKED ISSUE #1773: Cannot load project using `--project` argument
### What did you do?
Started IDE passing `--project Orders` CLI argument.

### What did you expect to see?
IDE opening project named `Orders` (which was present in the proper directory)

### What did you see instead?
IDE displayed welcome screen.

### Enso Version
Frontend:
    Version:  1.0.0
    Build:    405a6b2f
    Electron: 11.1.1
    Chrome:   87.0.4280.88

Backend:
    Enso Project Manager
    Version:    0.2.23
    Built with: scala-2.13.6 for GraalVM 21.1.0
    Built from: enso-0.2.23* @ 90ee83b9f0f4b72511f089d8648d2f9761d9c1a7
    Built on:   Windows 10 (amd64)

### LINKED ISSUE #3089: Cannot load project using `--project` argument
### What did you do?
Started IDE passing `--project Orders` CLI argument.

### What did you expect to see?
IDE opening project named `Orders` (which was present in the proper directory)

### What did you see instead?
IDE displayed welcome screen.

### Enso Version
Frontend:
    Version:  1.0.0
    Build:    405a6b2f
    Electron: 11.1.1
    Chrome:   87.0.4280.88

Backend:
    Enso Project Manager
    Version:    0.2.23
    Built with: scala-2.13.6 for GraalVM 21.1.0
    Built from: enso-0.2.23* @ 90ee83b9f0f4b72511f089d8648d2f9761d9c1a7
    Built on:   Windows 10 (amd64)

### PR DESCRIPTION
**Pull request by 4e6**
### Pull Request Description

[ci no changelog needed]

close #1773 

`--project` flag sets the `project` field in the global config. IDE will skip the welcome screen and start the WASM when the project field is set.

### Checklist
Please include the following checklist in your PR:

- [ ] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [x] The documentation has been updated if necessary.
- [ ] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [x] All code has been manually tested in the IDE.
- [ ] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://airtable.com/shr7KPRypRpanF7TO).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://airtable.com/shr7KPRypRpanF7TO).

### CODE REVIEW

**Review by mwu-tow — APPROVED** [review]

File: src/js/lib/content/src/index.ts [hunk 1]
```diff
@@ -955,20 +955,25 @@ API.main = async function(inputConfig: any) {
     config.updateFromObject(inputConfig)
     config.updateFromObject(urlConfig)
 
+    const runEntryPoint = async () => {
```
Comment (MichaelMauderer) [inline src/js/lib/content/src/index.ts]: Can this not be written as a `function` instead of an alignment of a closure?

Comment (4e6) [reply src/js/lib/content/src/index.ts]: Yes, I refactored it as a function :+1:

**Review by MichaelMauderer — APPROVED** [review]

**Review by wdanilo — APPROVED** [review]
